# Generated by Django 4.1.4 on 2023-05-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appoinment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("1", "sat"),
                            ("2", "sun"),
                            ("3", "mod"),
                            ("4", "tues"),
                            ("5", "wed"),
                            ("6", "thirs"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("1", "10"),
                            ("2", "10:30"),
                            ("3", "11"),
                            ("4", "11:30"),
                            ("5", "12"),
                            ("6", "12:30"),
                            ("7", "1"),
                            ("8", "1:30"),
                            ("9", "2"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="mobile",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Specialty",
        ),
        migrations.AddField(
            model_name="appoinment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointments.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appoinment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointments.patient"
            ),
        ),
    ]
