# Generated by Django 4.1.4 on 2023-05-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_remove_appoinment_patient_appoinment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="available_days",
            field=models.CharField(
                choices=[
                    ("1", "Saturday"),
                    ("2", "Sunday"),
                    ("3", "Monday"),
                    ("4", "Tuesday"),
                    ("5", "Wednesday"),
                    ("6", "Thursday"),
                    ("7", "Friday"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
