# Generated by Django 4.1.4 on 2023-05-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_doctor_available_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="appoinment",
            name="booked",
            field=models.BooleanField(default=False),
        ),
    ]
