# Generated by Django 4.1.4 on 2023-05-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_appoinment_booked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="available_days",
        ),
    ]
