# Generated by Django 4.1.4 on 2023-05-14 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_alter_appoinment_day_alter_appoinment_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appoinment",
            name="day",
        ),
        migrations.AddField(
            model_name="appoinment",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="appoinment",
            name="time",
            field=models.CharField(
                choices=[
                    ("10-10:30", "10-10:30"),
                    ("10:30-11", "10:30-11"),
                    ("11-11:30", "11-11:30"),
                    ("11:30-12", "11:30-12"),
                    ("12-12:30", "12-12:30"),
                    ("12:30-1", "12:30-1"),
                    ("1-1:30", "1-1:30"),
                    ("1:30-2", "1:30-2"),
                ],
                max_length=15,
            ),
        ),
    ]
